### ISSUE TITLE
Amar pay child widget position

### ISSUE THREAD

**Issue by muhib349** [sanjidbillah/aamarpay#1]
When I use a widget as child on **AamarpayData**, my child widget gets some height on its upper position. Why is that??
I've seen your code and found that **AamarpayData** use `SizedBox(height: 80)` in a column widget. How can resolve my issue??

**Comment by sanjidbillah** [comment]
Soon i will fix it. @muhib349

**Comment by sanjidbillah** [comment]
@muhib349  Check the latest version
