### ISSUE TITLE
Receiver: Instance of '_TypeError'

### ISSUE THREAD

**Issue by emondd4** [sanjidbillah/aamarpay#10]
Receiver: Instance of '_TypeError'
Tried calling: message
Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
    _AamarpayState.build.<anonymous closure>.<anonymous closure> (package:aamarpay/src/aamarpay.dart:143:57)
    _FutureListener.handleError (dart:async/future_impl.dart:181:22)
    Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
    Future._propagateToListeners (dart:async/future_impl.dart:894:13)
    Future._completeError (dart:async/future_impl.dart:674:5)
<asynchronous suspension>

Flutter Version: 3.24.0
Dart: 3.5.0

**Comment by najibahmed** [comment]
**ERROR: flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class '_TypeError' has no instance getter 'message'.
Receiver: Instance of '_TypeError'**
Tried calling: message
     Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
  _AamarpayState.build.<anonymous closure>.<anonymous closure> (package:aamarpay/src/aamarpay.dart:143:57)
   _FutureListener.handleError (dart:async/future_impl.dart:181:22)
     Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
     Future._propagateToListeners (dart:async/future_impl.dart:894:13)
    Future._completeError (dart:async/future_impl.dart:674:5)
: <asynchronous suspension>

Flutter version 3.22.2 
Dart version 3.4.3
<Same problem here!!>

**Comment by sanjidbillah** [comment]
@najibahmed @emondd4 

I have fixed it and provided a new version. Please check it.
