### ISSUE TITLE
having error 

### ISSUE THREAD

**Issue by Rafid-tawhid** [sanjidbillah/aamarpay#6]
![amar_pay](https://user-images.githubusercontent.com/55914303/191490282-f25667bd-fdb4-41da-9bb9-90c0c4c00699.PNG)
![amar_pay](https://user-images.githubusercontent.com/55914303/191490316-87af7f84-990c-424f-b8ad-0e21dfe53453.PNG)

**Why this error ??### ### ******
![amar_pay](https://user-images.githubusercontent.com/55914303/191490437-f01cfdac-cdea-42e2-a065-70df667494c6.PNG)

**Comment by sanjidbillah** [comment]
Did you import aamarpay?

**Comment by Rafid-tawhid** [comment]
yesterday i cant even import the package..  today i import successfully but a new problem arrived...
![payment_error](https://user-images.githubusercontent.com/55914303/191660426-9b2f8161-0984-4fb9-9936-33f5e00d48ec.png)
![payment_error](https://user-images.githubusercontent.com/55914303/191660462-441aa6ae-fcd6-41ed-abf6-bd95d759057e.png)

**Comment by Rafid-tawhid** [comment]
problem solved .. thank u
