### ISSUE TITLE
SDK ">=2.7.0 <3.0.0" is showing this error

### ISSUE THREAD

**Issue by farjanul** [sanjidbillah/aamarpay#8]
**SDK ">=2.7.0 <3.0.0" is showing this error.**

Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebStorageHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:2036:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebViewHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:289:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1013:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.pigeon.dart:1061:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.pigeon.dart:1087:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.pigeon.dart:1113:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.pigeon.dart:1239:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.pigeon.dart:1263:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setDisplayZoomControls (package:webview_flutter_android/src/android_webview.pigeon.dart:1288:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setBuiltInZoomControls (package:webview_flutter_android/src/android_webview.pigeon.dart:1313:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebViewClientHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1476:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setUserAgentString (package:webview_flutter_android/src/android_webview.pigeon.dart:1163:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #1      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #2      WebViewAndroidPlatformController.updateSettings (package:webview_flutter_android/webview_android_widget.dart:275:5)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebSettingsHostApi.setMediaPlaybackRequiresUserGesture (package:webview_flutter_android/src/android_webview.pigeon.dart:1189:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      DownloadListenerHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1749:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #1      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #2      WebView.setDownloadListener (package:webview_flutter_android/src/android_webview.dart:379:5)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebChromeClientHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1861:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #1      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #2      WebView.setWebChromeClient (package:webview_flutter_android/src/android_webview.dart:399:5)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13239): #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.pigeon.dart:401:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): 
E/flutter (13239): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter (13239): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:189)
E/flutter (13239): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (13239): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (13239): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (13239): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (13239): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (13239): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (13239): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (13239): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (13239): 	at android.os.Looper.loop(Looper.java:236)
E/flutter (13239): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/flutter (13239): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13239): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter (13239): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (13239): , null, null)
E/flutter (13239): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (13239): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1134:18)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:762:5)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #4      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1062:7)
E/flutter (13239): <asynchronous suspension>
E/flutter (13239): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:179:29)
E/flutter (13239): <asynchronous suspension>

**Comment by sanjidbillah** [comment]
Make it `sdk: ">=2.12.0 <3.0.0"`

**Comment by farjanul** [comment]
working
